steps:
# Step 1: Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build',
      '-t',
      'us-central1-docker.pkg.dev/terraform-practice-498312/task-repo/app:$BUILD_ID',
      '.'
    ]
 
# Step 2: Push image
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'push',
      'us-central1-docker.pkg.dev/terraform-practice-498312/task-repo/app:$BUILD_ID'
    ]

# Step 3: Update your VM instance to run the container
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'compute', 'instances', 'update-container', 'container-vm',
      '--zone=us-central1-a',
      '--container-image=us-central1-docker.pkg.dev/terraform-practice-498312/task-repo/app:$BUILD_ID'
    ]
 
options:
  logging: CLOUD_LOGGING_ONLY
  